soil_on_site_notification.get_pending_notification:
    path:     /pending/{agent_uri}
    defaults: { _controller: soil_notification.controller.pending_notification:getAgentNotificationAction }
    methods: [GET]
    requirements:
        agent_uri: .+


soil_on_site_notification.notification_set_shown:
    path:     /shown/{notification_id}
    defaults: { _controller: soil_notification.controller.pending_notification:setNotificationShownAction }
    methods: [GET]

soil_on_site_notification.notification_forget:
    path:     /forget/{notification_id}
    defaults: { _controller: soil_notification.controller.pending_notification:forgetNotificationAction }
    methods: [GET]
