services:
    soil_notification.controller.pending_notification:
        class: Soil\OnSiteNotificationBundle\Controller\PendingNotificationController
        arguments: [@soil_on_site_notification.service.notification_manager]

    soil_on_site_notification.service.notification_manager:
        class: Soil\OnSiteNotificationBundle\Service\NotificationManager
        arguments: [@doctrine_mongodb]


